maxwillkelly/Agile-Coursework

web/pages/studies/questionnaire/answer/[id].jsx
web/pages/studies/questionnaire/answer/thanks.jsx

Page also loads automatically when you click "submit".

Created a thank you page for completion of a questionnaire.

---

web/components/Login.jsx
web/components/Navigation.jsx
web/components/questionnaire/AddQuestionForm.jsx
web/components/questionnaire/AddTextSection.jsx
web/components/questionnaire/Question.jsx
web/components/questionnaire/TitleForm.jsx
web/components/styles/admin.module.scss
web/components/styles/login.module.scss
web/components/styles/navbar.module.scss
web/components/styles/questionnaire.module.scss
web/components/users/UserList.jsx
web/components/users/UserListSingle.jsx
web/components/users/UserProfile.jsx
web/pages/admin.jsx
web/pages/studies.jsx
web/styles/admin.module.scss
web/styles/studies.module.scss

- Studies uses SCSS
- Admin uses SCSS
- Index uses SCSS
-All components use SCSS

Converted most pages to use SCSS styling instead of bootstrap classes

---

web/pages/studies/[studyId].jsx
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/edit.jsx
web/styles/questionnaire-creator.module.scss
web/styles/studies.module.scss

- Questionnaire creation uses SCSS
- Study management page uses SCSS

All pages now use SCSS instead of bootstrap classes.

---

server/src/graphql-schemas/study.js
web/mutations/study.js
web/pages/studies/[studyId].jsx
web/styles/studies.module.scss

- You can now set permissions for staff levels on a study-by-study basis
- These settings will actually be stored in the database now

Permissions per study.

---

web/components/MainBreadcrumb.jsx
web/components/Spinner.jsx
web/components/study/VideoNotes.jsx
web/package.json
web/pages/studies/[studyId].jsx
web/pages/studies/[studyId]/videos/[videoNotesId].jsx
web/queries/video.js
web/styles/globals.scss
web/yarn.lock

- Implements video-react **will require yarn to be run to get new dependency**
- Adds a video notes list to the study page
- Adds the video notes page which displays the video from the appropriate video note
- Sets up the breadcrumb system for video links
- Extracts a spinner component to be used across most pages

Sets up Video List on Study Page and Video Page

---

server/src/func/videoNote.js
server/src/graphql-schemas/questionnaire.js
server/src/graphql-schemas/response.js
server/src/graphql-schemas/videoNotes.js
server/src/schema.js

- Add Create, Edit, Query GraphQL calls to API for VideoNotes
- Add the Ability to get responses to a questionnaire grouped by questions
- added Functions for assisting in data delivery of videoNotes

Create of Video API

---

.gitignore
web/pages/studies/[studyId].jsx
web/styles/studies.module.scss

- Moved the "Add staff" card to the left column
- Added a little margin on top as well

Little bit of CSS on the study permissions thingy

---

web/components/study/AddStaff.jsx
web/components/study/Permissions.jsx
web/components/study/Questionnaires.jsx
web/components/study/StaffList.jsx
web/components/study/StudyInfo.jsx
web/pages/studies/[studyId].jsx

- Separated each component into its own file
- Things like the questionnaire table, which are comprised of multiple smaller components, exist within the same file since they're closely related
- The button to create a questionnaire redirected you to a non-existent page, which I have now fixed (you go to the editing page for your new questionnaire).

The [studyID] page is now more modular and is broken up into proper components

---

server/src/func/permissionsChecker.js
server/src/func/staff.js
server/src/func/videoNote.js
server/src/graphql-schemas/response.js
server/src/graphql-schemas/videoNotes.js

- Add API for getting number of responses
- Reusable function for checking permissions 
- videoNotes now check perms 
- Notes in videoNotes are now ordered by timestamp

API Updates

---

web/components/questionnaire/Answer.jsx
web/components/questionnaire/Response.jsx
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/answer.jsx
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/responses.jsx

- Removed Breadcrumb from answer page
- Removed Text sections from responses page
- Check if answer in responses page didn't have any responses instead of showing empty graph

Responses Page, Thank You Page and Answer Page updates

---

server/src/func/bucketUpload.js
server/src/graphql-schemas/response.js
server/src/graphql-schemas/videoNotes.js

- Function to create signed links to S3 objects
- CSV downloads now use S3 signed URLs instead of being publicly open 
- Export videoNotes as CSV

AWS S3 object URL signing & Export videoNotes

---

web/components/questionnaire/Question.jsx
web/components/styles/questionnaire.module.scss
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/edit.jsx

- Save button on text sections
- Question requirement checkbox (non-functional)
- Small UX fixes
- Question type dropdown menu
- Questionnaire creation page now has icon

Questionnaire tweaks

---

web/components/questionnaire/Answer.jsx
web/components/questionnaire/RadioInput.jsx
web/components/styles/questionnaire.module.scss
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/answer.jsx
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/edit.jsx
web/queries/questionnaire.js
web/yarn.lock

- questions will show as red if invalid
- questionnaire will not submit unless entire form is valid

Questionnaire Form Required Validation

---

web/components/questionnaire/Question.jsx
web/mutations/questionnaire.js
web/package.json
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/edit.jsx
web/queries/questionnaire.js

- Question cards are draggable
- Order updates automatically!
- **NEW DEPENDENCY. RUN `yarn install` OR `npm install`!!!!!!!!!!!!!!!!!!!!!**

Question ordering 😎

---

web/components/questionnaire/Question.jsx
web/components/styles/questionnaire.module.scss
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/edit.jsx

- Scrollable questions
- Bit o margin
- Title form takes up top

Put ramsay's sick styling back in place

---

web/components/study/Questionnaires.jsx
web/components/study/VideoNotes.jsx
web/mutations/video.js
web/queries/video.js
web/yarn.lock

- Added Video Notes Export
- Added ability to create video Notes
- ability to delete a videonotes

Create, Delete and Export Video Notes

---

web/components/questionnaire/AddQuestionForm.jsx
web/components/questionnaire/Question.jsx
web/mutations/questionnaire.js
web/pages/studies/[studyId]/questionnaire/[questionnaireId]/edit.jsx

- Add question button
- Required question checkbox

Fixed addquestion and maybe required questions

---

web/components/questionnaire/Question.jsx
web/components/study/AddStaff.jsx
web/components/study/Questionnaires.jsx
web/components/styles/questionnaire.module.scss
web/mutations/study.js
web/pages/studies.jsx
web/pages/studies/[studyId].jsx
web/yarn.lock

Fixing some changes in study area

---

web/pages/ethics.jsx

Getting correct id for sprint review

---

server/src/graphql-schemas/questionnaire.js
server/src/graphql-schemas/study.js
server/src/graphql-schemas/videoNotes.js

- Fix perms checking error 
- Creation apis fix, return error
- move StudyID from create videoNote to outside args

random odd and end api fixes
